services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /pool/data:/data
    networks:
      - arr
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /pool/data:/data
    networks:
      - arr
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /pool/data/usenet:/data/usenet:rw
    networks:
      - arr

  profilarr:
    image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
    container_name: profilarr
    ports:
        - 6868:6868
    volumes:
        - /opt/stacks/profilarr/config:/config # Replace with your actual path
    environment:
        - TZ=Europe/Brussels # Set your timezone
    restart: unless-stopped
    networks:
      - arr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Europe/Brussels
    ports:
        - 5055:5055
    volumes:
        - /opt/stacks/jellyseerr/config:/app/config
    networks:
     - frontend
     - arr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`request.02082004.xyz`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.tls.certresolver=letencrypt"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
    restart: unless-stopped

networks:
  frontend:
    external: true
  arr:
    internal: true