services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      UID: "1000"
      GID: "1000"
      MEMORY: "6G"
    volumes:
      - /opt/appdata/data/minecraft:/data