services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      UID: "1000"
      GID: "1000"
    volumes:
      - /opt/appdata/data/minecraft:/data