services:
  nzbdav:
    image: ghcr.io/nzbdav-dev/nzbdav
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - /opt/stacks/nzbdav/config:/config
    restart: unless-stopped


volumes:
  nzbdav:
    driver: rclone
    driver_opts:
      remote: 'nzb-dav:'
      allow_other: 'true'
      vfs_cache_mode: off
      dir_cache_time: 1s
      allow_non_empty: 'true'
      uid: 1000
      gid: 1000
