services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/appdata/config/jellyfin:/config
      - /vault/data/media/tv:/data/tvshows
      - /vault/data/media/movies:/data/movies
    networks:
      - caddy
    runtime: nvidia


  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /opt/appdata/config/jellyseerr:/app/config
    networks:
      - arr
      - caddy
    depends_on:
      - jellyfin
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  caddy:
    external: true
  arr:
    external: true

